services:
  movieraterbackend-debug:
    image: movieraterbackend-debug
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        YOUR_ENV: development
    volumes:
      - ./app/:/app/app
      - ./alembic/:/app/alembic
      - ./tests/:/app/tests
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5678 -m uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 9090"]
    ports:
      - 9090:9090
      - 5678:5678
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 9091:5432
volumes:
    postgres_data:
